ALTER TABLE app_user
    ADD COLUMN IF NOT EXISTS birthday DATE,
    ADD COLUMN IF NOT EXISTS gender SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS female_role SMALLINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS work_start_year INT;
